// Build design tokens (DTCG JSON) into CSS custom properties, SCSS aliases, and typed TS.
//
// Parity-first: we register NO value transforms, only a name transform that restores each
// token's original css variable name from `$extensions["com.hrm"].cssVar`. Values therefore
// pass through byte-identical to the source SCSS. Style Dictionary still resolves `{alias}`
// references, so semantic tokens emit as `var(--primitive)` and cascade under [data-theme].

import StyleDictionary from 'style-dictionary'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const PKG = dirname(fileURLToPath(import.meta.url))
const val = (t) => (t.$value !== undefined ? t.$value : t.value)

// --- name transform: use the recorded css var name verbatim -------------------
StyleDictionary.registerTransform({
  name: 'name/hrm',
  type: 'name',
  transform: (token) => token.$extensions?.['com.hrm']?.cssVar ?? token.path.join('-')
})

StyleDictionary.registerTransformGroup({ name: 'hrm', transforms: ['name/hrm'] })

// --- SCSS alias partial: $token: var(--token); (themeable, autocompletes) -----
StyleDictionary.registerFormat({
  name: 'hrm/scss-aliases',
  format: ({ dictionary }) =>
    '// AUTOGENERATED by @hrm/design-tokens — do not edit by hand.\n' +
    dictionary.allTokens.map((t) => `$${t.name}: var(--${t.name});`).join('\n') +
    '\n'
})

// --- typed TS tokens (resolved light values) ----------------------------------
StyleDictionary.registerFormat({
  name: 'hrm/ts',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `  '${t.name}': ${JSON.stringify(String(val(t)))}`)
    return (
      '// AUTOGENERATED by @hrm/design-tokens — do not edit by hand.\n' +
      'export const tokens = {\n' +
      lines.join(',\n') +
      '\n} as const\n\n' +
      'export type TokenName = keyof typeof tokens\n'
    )
  }
})

// --- semantic SCSS block for the library --------------------------------------
// Emits `--semantic: var(--primitive);` so semantics stay references and cascade under
// [data-theme]. Parametrized by options.selector (`:root` vs `[data-theme="dark"]`) and
// options.filterDir (which source dir's tokens to emit). Returns just the selector block;
// build.mjs composes the final partial. Colors only for now.
StyleDictionary.registerFormat({
  name: 'hrm/semantic-scss',
  format: ({ dictionary, options }) => {
    const selector = options?.selector || ':root'
    const dir = options?.filterDir || '/semantic/'
    // path -> original css var name, so an alias like {color.raw.5} maps to --color-5.
    const cssVarByPath = new Map()
    for (const t of dictionary.allTokens) {
      const cv = t.$extensions?.['com.hrm']?.cssVar
      if (cv) cssVarByPath.set(t.path.join('.'), cv)
    }
    const line = (t) => {
      const ref = t.original?.$value ?? t.$value
      const m = typeof ref === 'string' && ref.match(/^\{(.+)\}$/)
      if (m) {
        const target = cssVarByPath.get(m[1]) || m[1].replace(/^color\./, '').split('.').join('-')
        return `  --${t.name}: var(--${target});`
      }
      return `  --${t.name}: ${String(val(t))};` // literal (non-alias) value
    }
    const chosen = dictionary.allTokens.filter((t) => (t.filePath || '').includes(dir))
    return `${selector} {\n${chosen.map(line).join('\n')}\n}\n`
  }
})

const base = { usesDtcg: true, log: { verbosity: 'silent' } }

// Light: primitives + semantics -> :root (semantics as var() references)
const light = new StyleDictionary({
  ...base,
  source: [`${PKG}/tokens/primitive/**/*.json`, `${PKG}/tokens/semantic/**/*.json`],
  platforms: {
    css: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/css/`,
      files: [
        {
          destination: '_light.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: true }
        }
      ]
    },
    scss: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/scss/`,
      files: [{ destination: '_tokens.scss', format: 'hrm/scss-aliases' }]
    },
    ts: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/ts/`,
      files: [{ destination: 'tokens.ts', format: 'hrm/ts' }]
    },
    // Light semantic block (:root) -> composed into the library partial below.
    lib: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/lib/`,
      files: [
        {
          destination: '_semantic-light.scss',
          format: 'hrm/semantic-scss',
          options: { selector: ':root', filterDir: '/semantic/' }
        }
      ]
    }
  }
})

// Dark: theme overrides only -> [data-theme="dark"] (literal values)
const dark = new StyleDictionary({
  ...base,
  source: [`${PKG}/tokens/themes/dark/**/*.json`],
  platforms: {
    css: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/css/`,
      files: [
        {
          destination: '_dark.css',
          format: 'css/variables',
          options: { selector: '[data-theme="dark"]', outputReferences: false }
        }
      ]
    }
  }
})

// Dark semantic overrides -> [data-theme="dark"] block. Sources dark primitives so the
// alias references (incl. dark-only --color-1/--color-5) resolve without collisions.
const darkSemantic = new StyleDictionary({
  ...base,
  source: [`${PKG}/tokens/themes/dark/**/*.json`, `${PKG}/tokens/themes/dark-semantic/**/*.json`],
  platforms: {
    lib: {
      transformGroup: 'hrm',
      buildPath: `${PKG}/build/lib/`,
      files: [
        {
          destination: '_semantic-dark.scss',
          format: 'hrm/semantic-scss',
          options: { selector: '[data-theme="dark"]', filterDir: '/dark-semantic/' }
        }
      ]
    }
  }
})

await light.buildAllPlatforms()
await dark.buildAllPlatforms()
await darkSemantic.buildAllPlatforms()

// Concatenate primitives into a single stylesheet matching the library's single-file model.
const lightCss = readFileSync(`${PKG}/build/css/_light.css`, 'utf8')
const darkCss = readFileSync(`${PKG}/build/css/_dark.css`, 'utf8')
writeFileSync(`${PKG}/build/css/tokens.css`, lightCss + '\n' + darkCss)

// Compose the semantic partial (:root light + [data-theme="dark"] overrides) into the library.
const semHeader =
  '// AUTOGENERATED by @hrm/design-tokens (pnpm tokens:build) — do not edit by hand.\n' +
  '// Semantic (intent) tokens. :root defines the light value; [data-theme="dark"] overrides\n' +
  '// the ones that genuinely differ in dark. Components reference only these semantic vars.\n'
const semLight = readFileSync(`${PKG}/build/lib/_semantic-light.scss`, 'utf8')
const semDark = readFileSync(`${PKG}/build/lib/_semantic-dark.scss`, 'utf8')
writeFileSync(
  `${PKG}/../../src/assets/styles/tokens/_semantic.scss`,
  semHeader + semLight + '\n' + semDark
)

console.log('Built: build/css/tokens.css, build/scss/_tokens.scss, build/ts/tokens.ts')
console.log('Wrote: src/assets/styles/tokens/_semantic.scss (:root + [data-theme="dark"])')
